# Generated by Django 6.0 on 2025-12-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('intrusion', 'intrusion'), ('malware', 'malware'), ('anomaly', 'anomaly')], max_length=50),
        ),
    ]
