# Generated by Django 6.0 on 2025-12-24 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Acknowledged', 'Acknowledged'), ('Resolved', 'Resolved')], default='Open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='events.event')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='alerts_aler_status_2a92cb_idx')],
            },
        ),
    ]
